### ISSUE TITLE
Some type of visual glitch?

### ISSUE THREAD

**Issue by unloopedmido** [foxlet/macOS-Simple-KVM#381]
I don't know what the problem here is, but whenever I run my KVM, This happens to the display
![VirtualMachineGlitch?](https://user-images.githubusercontent.com/73798815/101991092-6bcbc780-3cbb-11eb-984c-ba3bbf359fee.png)

**Comment by adrianaryaputra** [comment]
i got the same problem after changing my config.plist resolution to 1920x1080...

**Comment by unloopedmido** [comment]
Did it get fixed by now?

**Comment by bishoyroufael** [comment]
I am having the same issue, any ideas about solutions to this?

**Comment by adrianaryaputra** [comment]
Still have the same issue... i’m using default resolution because of this issue..

**Comment by jrandiny** [comment]
Possible duplicate of #51 ?

**Comment by adrianaryaputra** [comment]
> Possible duplicate of #51 ?

I’m running from basic.sh tho..

**Comment by jrandiny** [comment]
However the original issue reporter is using virt-manager. Have you change the ovmf configuration?
